version: 2
updates:
  - package-ecosystem: npm
    directory: "/javascript"
    schedule:
      interval: "daily"
    reviewers:
      - direisc
    assignees:
      - direisc
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - direisc
    assignees:
      - direisc
